### ISSUE TITLE
AttributeError: 'Lookahead' object has no attribute 'weights'

### ISSUE THREAD

**Issue by iamzhangyunlu** [nsarang/lookahead_keras#1]
Hi, thank you for your codes first! And when I use your code to replace adam optimizer in my project, something wrong like the title I wrote: **AttributeError: 'Lookahead' object has no attribute 'weights'**. Please tell me what should I do? @nsarang

**Comment by nsarang** [comment]
Can you give me details about your code and versions of Keras and Tensorflow you are using?
I must note that this implementation relies on Tensorflow 1.X as backend.

To use adam with Lookahead:
```python
from keras.optimizers import Adam
from lookahead import Lookahead

lookopt = Lookahead(optimizer=Adam(), k=3, alpha=0.5)
```

**Comment by iamzhangyunlu** [comment]
Traceback (most recent call last):
  File "/media/student4/46208D3E208D35C9/vgg19分类/vgg19.py", line 117, in <module>
    history_ft = transfer.train_model(model, 10, train_generator, 1000, validation_generator, 100, 'vgg19_model_weights.h5', is_load_model=True)

  File "/media/student4/46208D3E208D35C9/vgg19分类/vgg19.py", line 75, in train_model
    model.save(model_url, overwrite=True)

  File "/home/student4/anaconda3/envs/zyl/lib/python3.6/site-packages/keras/engine/network.py", line 1152, in save
    save_model(self, filepath, overwrite, include_optimizer)

  File "/home/student4/anaconda3/envs/zyl/lib/python3.6/site-packages/keras/engine/saving.py", line 449, in save_wrapper
    save_function(obj, filepath, overwrite, *args, **kwargs)

  File "/home/student4/anaconda3/envs/zyl/lib/python3.6/site-packages/keras/engine/saving.py", line 541, in save_model
    _serialize_model(model, h5dict, include_optimizer)

  File "/home/student4/anaconda3/envs/zyl/lib/python3.6/site-packages/keras/engine/saving.py", line 187, in _serialize_model
    symbolic_weights = getattr(model.optimizer, 'weights')

AttributeError: 'Lookahead' object has no attribute 'weights'

**Comment by iamzhangyunlu** [comment]
@nsarang the version of Tensorflow is 2.0.0 and the version of tensorflow-gpu is 1.14.0 and the version of keras is 2.3.1 and I **have changed tensorflow version from 2.0.0 to 1.14.0** but the problem is still there...

**Comment by nsarang** [comment]
Thanks for the feedback. It's fixed now.

**Comment by iamzhangyunlu** [comment]
@nsarang I'm sorry, a new problem showed up as below:

Traceback (most recent call last):
  File "/media/student4/46208D3E208D35C9/vgg19分类/vgg19.py", line 117, in <module>
    history_ft = transfer.train_model(model, 10, train_generator, 1000, validation_generator, 100, 'vgg19_model_weights.h5', is_load_model=True)

  File "/media/student4/46208D3E208D35C9/vgg19分类/vgg19.py", line 76, in train_model
    model = load_model(model_url)

  File "/home/student4/anaconda3/envs/zyl/lib/python3.6/site-packages/keras/engine/saving.py", line 492, in load_wrapper
    return load_function(*args, **kwargs)

  File "/home/student4/anaconda3/envs/zyl/lib/python3.6/site-packages/keras/engine/saving.py", line 584, in load_model
    model = _deserialize_model(h5dict, custom_objects, compile)

  File "/home/student4/anaconda3/envs/zyl/lib/python3.6/site-packages/keras/engine/saving.py", line 348, in _deserialize_model
    custom_objects=custom_objects)

  File "/home/student4/anaconda3/envs/zyl/lib/python3.6/site-packages/keras/optimizers.py", line 833, in deserialize
    printable_module_name='optimizer')

  File "/home/student4/anaconda3/envs/zyl/lib/python3.6/site-packages/keras/utils/generic_utils.py", line 140, in deserialize_keras_object
    ': ' + class_name)

ValueError: Unknown optimizer: Lookahead

**Comment by iamzhangyunlu** [comment]
Is that the problem of Keras' version? What's your version of keras? I think my version is too new, I'll downgrade to 2.2.4 from 2.3.1

**Comment by nsarang** [comment]
The version of Keras is not a problem. You'd be okay with a Tensorflow 1.X backend.

Since I personally prefer to use **save_weights** and **load_weights** methods instead of **save** and **load_model,** I hadn't tested the other ones. These methods are now supported.

Lookahead is a custom optimizer. So in your **load_model** call you have two options:
1. Set the compile flag to False:
```python
keras.models.load_model(model_path, compile=False)
```
2. Pass Lookahead as a custom object:
```python
keras.models.load_model(model_path, custom_objects={'Lookahead': Lookahead})
```

Let me know if there are any problems.

**Comment by iamzhangyunlu** [comment]
Thank you! I am running another program. When it's finished, I will try your methods and give feedback as soon, thanks again!

**Comment by iamzhangyunlu** [comment]
Hi there, I've tried your methods and the problem is as below:

Traceback (most recent call last):
  File "/home/student4/vgg19分类/vgg19.py", line 117, in <module>
    history_ft = transfer.train_model(model, 10, train_generator, 1000, validation_generator, 100, 'vgg19_model_weights.h5', is_load_model=True)

  File "/home/student4/vgg19分类/vgg19.py", line 83, in train_model
    validation_steps=validation_steps)

  File "/home/student4/anaconda3/envs/zyl/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)

  File "/home/student4/anaconda3/envs/zyl/lib/python3.6/site-packages/keras/engine/training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)

  File "/home/student4/anaconda3/envs/zyl/lib/python3.6/site-packages/keras/engine/training_generator.py", line 40, in fit_generator
    model._make_train_function()

  File "/home/student4/anaconda3/envs/zyl/lib/python3.6/site-packages/keras/engine/training.py", line 496, in _make_train_function

    raise RuntimeError('You must compile your model before using it.')
RuntimeError: You must compile your model before using it.

**Comment by nsarang** [comment]
If you chose the first option and set the compile flag to False, then you should compile your model again after loading it.

**Comment by iamzhangyunlu** [comment]
then why set the compile flag False? Sorry I don’t understand😂

________________________________
发件人: Nima Sarang <notifications@github.com>
发送时间: Friday, November 22, 2019 2:12:34 PM
收件人: nsarang/lookahead_keras <lookahead_keras@noreply.github.com>
抄送: iamzhangyunlu <zhangyunlu123@live.com>; Author <author@noreply.github.com>
主题: Re: [nsarang/lookahead_keras] AttributeError: 'Lookahead' object has no attribute 'weights' (#1)


If you choose the first option and set the compile flag to False, then you should compile your model again after loading it.

**Comment by iamzhangyunlu** [comment]
> If you choose the first option and set the compile flag to False, then you should compile your model again after loading it.

@nsarang Hi，I do as what you say, **copy model.compile(...) and paste after model=load_model(...)**, it worked， thank you so much!
